version: '2'

services:
  kedro:
    build:
      context: .
    volumes:
      - $PWD:/usr/src/app
    ports:
      - '4141:4141'
      - '8888:8888'
  db:
    image: postgres:13-alpine
    ports:
      - '54323:5432'
    environment:
      POSTGRES_PASSWORD: docker
