[tool.kedro]
package_name = "factbook_data_pipeline"
project_name = "Factbook Data Pipeline"
project_version = "0.17.2"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 80
known_third_party = "kedro"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/factbook_data_pipeline -ra"""

[tool.black]
line-length = 80
