CREATE TABLE public.import(
    introduction_background text NULL
    ,communications_broadband_fixed_subscriptions_subscriptions_per_100_inhabitants text NULL
    ,communications_broadband_fixed_subscriptions_total text NULL
    ,communications_broadcast_media text NULL
    ,communications_communications_note text NULL
    ,communications_internet_country_code text NULL
    ,communications_internet_country_code_note text NULL
    ,communications_internet_users_note text NULL
    ,communications_internet_users_percent_of_population text NULL
    ,communications_internet_users_total text NULL
    ,communications_telecommunication_systems_domestic text NULL
    ,communications_telecommunication_systems_general_assessment text NULL
    ,communications_telecommunication_systems_international text NULL
    ,communications_telecommunication_systems_note text NULL
    ,communications_telecommunication_systems_overseas_departments text NULL
    ,communications_telephones_fixed_lines_subscriptions_per_100_inhabitants text NULL
    ,communications_telephones_fixed_lines_total_subscriptions text NULL
    ,communications_telephones_mobile_cellular_subscriptions_per_100_inhabitants text NULL
    ,communications_telephones_mobile_cellular_total_subscriptions text NULL
    ,economy_agricultural_products text NULL
    ,economy_agricultural_products_note text NULL
    ,economy_budget_expenditures text NULL
    ,economy_budget_note text NULL
    ,economy_budget_revenues text NULL
    ,economy_budget_surplus__or_deficit__ text NULL
    ,economy_budget_surplus__or_deficit___note text NULL
    ,economy_credit_ratings_fitch_rating text NULL
    ,economy_credit_ratings_moodys_rating text NULL
    ,economy_credit_ratings_note text NULL
    ,economy_credit_ratings_standard__poors_rating text NULL
    ,economy_current_account_balance_current_account_balance_2016 text NULL
    ,economy_current_account_balance_current_account_balance_2017 text NULL
    ,economy_current_account_balance_current_account_balance_2018 text NULL
    ,economy_current_account_balance_current_account_balance_2019 text NULL
    ,economy_current_account_balance_current_account_balance_2020 text NULL
    ,economy_debt_external text NULL
    ,economy_debt_external_debt_external_2003 text NULL
    ,economy_debt_external_debt_external_2004 text NULL
    ,economy_debt_external_debt_external_2008 text NULL
    ,economy_debt_external_debt_external_2010 text NULL
    ,economy_debt_external_debt_external_2012 text NULL
    ,economy_debt_external_debt_external_2013 text NULL
    ,economy_debt_external_debt_external_2014 text NULL
    ,economy_debt_external_debt_external_2015 text NULL
    ,economy_debt_external_debt_external_2016 text NULL
    ,economy_debt_external_debt_external_2017 text NULL
    ,economy_debt_external_debt_external_2018 text NULL
    ,economy_debt_external_debt_external_2019 text NULL
    ,economy_debt_external_debt_external_31_december_2000 text NULL
    ,economy_debt_external_debt_external_31_december_2010 text NULL
    ,economy_debt_external_debt_external_31_december_2012 text NULL
    ,economy_debt_external_debt_external_31_december_2013 text NULL
    ,economy_debt_external_debt_external_31_december_2014 text NULL
    ,economy_debt_external_debt_external_31_december_2015 text NULL
    ,economy_debt_external_debt_external_31_december_2016 text NULL
    ,economy_debt_external_debt_external_31_december_2017 text NULL
    ,economy_debt_external_debt_external_31_december_2020 text NULL
    ,economy_debt_external_debt_external_fy1011 text NULL
    ,economy_debt_external_debt_external_june_2010 text NULL
    ,economy_debt_external_note text NULL
    ,economy_ease_of_doing_business_index_scores_enforcement_score text NULL
    ,economy_ease_of_doing_business_index_scores_overall_score text NULL
    ,economy_ease_of_doing_business_index_scores_starting_a_business_score text NULL
    ,economy_ease_of_doing_business_index_scores_trading_score text NULL
    ,economy_economic_overview text NULL
    ,economy_economy_of_the_area_administered_by_turkish_cypriots text NULL
    ,economy_exchange_rates text NULL
    ,economy_exchange_rates_currency text NULL
    ,economy_exchange_rates_exchange_rates_2010 text NULL
    ,economy_exchange_rates_exchange_rates_2012 text NULL
    ,economy_exchange_rates_exchange_rates_2013 text NULL
    ,economy_exchange_rates_exchange_rates_2014 text NULL
    ,economy_exchange_rates_exchange_rates_2015 text NULL
    ,economy_exchange_rates_exchange_rates_2016 text NULL
    ,economy_exchange_rates_exchange_rates_2017 text NULL
    ,economy_exchange_rates_exchange_rates_2018 text NULL
    ,economy_exchange_rates_exchange_rates_2019 text NULL
    ,economy_exchange_rates_exchange_rates_2020 text NULL
    ,economy_exchange_rates_note text NULL
    ,economy_exports_commodities text NULL
    ,economy_exports_exports_2004 text NULL
    ,economy_exports_exports_2010 text NULL
    ,economy_exports_exports_2011 text NULL
    ,economy_exports_exports_2012 text NULL
    ,economy_exports_exports_2013 text NULL
    ,economy_exports_exports_2014 text NULL
    ,economy_exports_exports_2015 text NULL
    ,economy_exports_exports_2016 text NULL
    ,economy_exports_exports_2017 text NULL
    ,economy_exports_exports_2018 text NULL
    ,economy_exports_exports_2019 text NULL
    ,economy_exports_exports_2020 text NULL
    ,economy_exports_note text NULL
    ,economy_exports_partners text NULL
    ,economy_fiscal_year text NULL
    ,economy_fiscal_year_note text NULL
    ,economy_gdp_composition_by_end_use_exports_of_goods_and_services text NULL
    ,economy_gdp_composition_by_end_use_government_consumption text NULL
    ,economy_gdp_composition_by_end_use_household_consumption text NULL
    ,economy_gdp_composition_by_end_use_imports_of_goods_and_services text NULL
    ,economy_gdp_composition_by_end_use_investment_in_fixed_capital text NULL
    ,economy_gdp_composition_by_end_use_investment_in_inventories text NULL
    ,economy_gdp_composition_by_end_use_note text NULL
    ,economy_gdp_composition_by_sector_of_origin_agriculture text NULL
    ,economy_gdp_composition_by_sector_of_origin_industry text NULL
    ,economy_gdp_composition_by_sector_of_origin_note text NULL
    ,economy_gdp_composition_by_sector_of_origin_services text NULL
    ,economy_gdp_official_exchange_rate text NULL
    ,economy_gdp_official_exchange_rate_note text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_1987 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_1989 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_1992 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_1993 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_1994 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_1995 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_1996 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_1997 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_1998 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_1999 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2000 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2001 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2002 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2003 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2004 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2005 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2006 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2007 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2008 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2009 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2010 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2011 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2012 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2013 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2014 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2015 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2016 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2017 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_2018 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_december_2017 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_gini_index_coefficient_distribution_of_family_income_fy2011 text NULL
    ,economy_gini_index_coefficient_distribution_of_family_income_note text NULL
    ,economy_gross_national_saving text NULL
    ,economy_gross_national_saving_gross_national_saving_2015 text NULL
    ,economy_gross_national_saving_gross_national_saving_2016 text NULL
    ,economy_gross_national_saving_gross_national_saving_2017 text NULL
    ,economy_gross_national_saving_gross_national_saving_2018 text NULL
    ,economy_gross_national_saving_gross_national_saving_2019 text NULL
    ,economy_gross_national_saving_note text NULL
    ,economy_household_income_or_consumption_by_percentage_share_highest_10 text NULL
    ,economy_household_income_or_consumption_by_percentage_share_lowest_10 text NULL
    ,economy_household_income_or_consumption_by_percentage_share_note text NULL
    ,economy_imports_commodities text NULL
    ,economy_imports_imports_2010 text NULL
    ,economy_imports_imports_2011 text NULL
    ,economy_imports_imports_2013 text NULL
    ,economy_imports_imports_2014 text NULL
    ,economy_imports_imports_2015 text NULL
    ,economy_imports_imports_2016 text NULL
    ,economy_imports_imports_2017 text NULL
    ,economy_imports_imports_2018 text NULL
    ,economy_imports_imports_2019 text NULL
    ,economy_imports_imports_2020 text NULL
    ,economy_imports_note text NULL
    ,economy_imports_partners text NULL
    ,economy_industrial_production_growth_rate text NULL
    ,economy_industrial_production_growth_rate_note text NULL
    ,economy_industries text NULL
    ,economy_industries_note text NULL
    ,economy_inflation_rate_consumer_prices text NULL
    ,economy_inflation_rate_consumer_prices_inflation_rate_consumer_prices_2010 text NULL
    ,economy_inflation_rate_consumer_prices_inflation_rate_consumer_prices_2013 text NULL
    ,economy_inflation_rate_consumer_prices_inflation_rate_consumer_prices_2014 text NULL
    ,economy_inflation_rate_consumer_prices_inflation_rate_consumer_prices_2015 text NULL
    ,economy_inflation_rate_consumer_prices_inflation_rate_consumer_prices_2016 text NULL
    ,economy_inflation_rate_consumer_prices_inflation_rate_consumer_prices_2017 text NULL
    ,economy_inflation_rate_consumer_prices_inflation_rate_consumer_prices_2018 text NULL
    ,economy_inflation_rate_consumer_prices_inflation_rate_consumer_prices_2019 text NULL
    ,economy_inflation_rate_consumer_prices_inflation_rate_consumer_prices_2020 text NULL
    ,economy_inflation_rate_consumer_prices_note text NULL
    ,economy_labor_force text NULL
    ,economy_labor_force_by_occupation text NULL
    ,economy_labor_force_by_occupation_agriculture text NULL
    ,economy_labor_force_by_occupation_farming_forestry_and_fishing text NULL
    ,economy_labor_force_by_occupation_industry text NULL
    ,economy_labor_force_by_occupation_industry_and_services text NULL
    ,economy_labor_force_by_occupation_managerial_professional_and_technical text NULL
    ,economy_labor_force_by_occupation_manufacturing text NULL
    ,economy_labor_force_by_occupation_manufacturing_extraction_transportation_and_crafts text NULL
    ,economy_labor_force_by_occupation_note text NULL
    ,economy_labor_force_by_occupation_other_services text NULL
    ,economy_labor_force_by_occupation_sales_and_office text NULL
    ,economy_labor_force_by_occupation_services text NULL
    ,economy_labor_force_by_occupation_tourism text NULL
    ,economy_labor_force_note text NULL
    ,economy_population_below_poverty_line text NULL
    ,economy_population_below_poverty_line_note text NULL
    ,economy_public_debt_note text NULL
    ,economy_public_debt_public_debt_2013 text NULL
    ,economy_public_debt_public_debt_2014 text NULL
    ,economy_public_debt_public_debt_2015 text NULL
    ,economy_public_debt_public_debt_2016 text NULL
    ,economy_public_debt_public_debt_2017 text NULL
    ,economy_public_debt_public_debt_2018 text NULL
    ,economy_public_debt_public_debt_2019 text NULL
    ,economy_public_debt_public_debt_2020 text NULL
    ,economy_public_debt_public_debt_fy2016 text NULL
    ,economy_public_debt_public_debt_fy2017 text NULL
    ,economy_real_gdp_growth_rate_note text NULL
    ,economy_real_gdp_growth_rate_real_gdp_growth_rate_2007 text NULL
    ,economy_real_gdp_growth_rate_real_gdp_growth_rate_2011 text NULL
    ,economy_real_gdp_growth_rate_real_gdp_growth_rate_2012 text NULL
    ,economy_real_gdp_growth_rate_real_gdp_growth_rate_2013 text NULL
    ,economy_real_gdp_growth_rate_real_gdp_growth_rate_2014 text NULL
    ,economy_real_gdp_growth_rate_real_gdp_growth_rate_2015 text NULL
    ,economy_real_gdp_growth_rate_real_gdp_growth_rate_2016 text NULL
    ,economy_real_gdp_growth_rate_real_gdp_growth_rate_2017 text NULL
    ,economy_real_gdp_growth_rate_real_gdp_growth_rate_2018 text NULL
    ,economy_real_gdp_growth_rate_real_gdp_growth_rate_2019 text NULL
    ,economy_real_gdp_growth_rate_real_gdp_growth_rate_2020 text NULL
    ,economy_real_gdp_per_capita_note text NULL
    ,economy_real_gdp_per_capita_real_gdp_per_capita_2007 text NULL
    ,economy_real_gdp_per_capita_real_gdp_per_capita_2008 text NULL
    ,economy_real_gdp_per_capita_real_gdp_per_capita_2009 text NULL
    ,economy_real_gdp_per_capita_real_gdp_per_capita_2013 text NULL
    ,economy_real_gdp_per_capita_real_gdp_per_capita_2014 text NULL
    ,economy_real_gdp_per_capita_real_gdp_per_capita_2015 text NULL
    ,economy_real_gdp_per_capita_real_gdp_per_capita_2016 text NULL
    ,economy_real_gdp_per_capita_real_gdp_per_capita_2017 text NULL
    ,economy_real_gdp_per_capita_real_gdp_per_capita_2018 text NULL
    ,economy_real_gdp_per_capita_real_gdp_per_capita_2019 text NULL
    ,economy_real_gdp_per_capita_real_gdp_per_capita_2020 text NULL
    ,economy_real_gdp_purchasing_power_parity text NULL
    ,economy_real_gdp_purchasing_power_parity_note text NULL
    ,economy_real_gdp_purchasing_power_parity_real_gdp_purchasing_power_parity_2008 text NULL
    ,economy_real_gdp_purchasing_power_parity_real_gdp_purchasing_power_parity_2009 text NULL
    ,economy_real_gdp_purchasing_power_parity_real_gdp_purchasing_power_parity_2013 text NULL
    ,economy_real_gdp_purchasing_power_parity_real_gdp_purchasing_power_parity_2014 text NULL
    ,economy_real_gdp_purchasing_power_parity_real_gdp_purchasing_power_parity_2015 text NULL
    ,economy_real_gdp_purchasing_power_parity_real_gdp_purchasing_power_parity_2016 text NULL
    ,economy_real_gdp_purchasing_power_parity_real_gdp_purchasing_power_parity_2017 text NULL
    ,economy_real_gdp_purchasing_power_parity_real_gdp_purchasing_power_parity_2018 text NULL
    ,economy_real_gdp_purchasing_power_parity_real_gdp_purchasing_power_parity_2019 text NULL
    ,economy_reserves_of_foreign_exchange_and_gold_note text NULL
    ,economy_reserves_of_foreign_exchange_and_gold_reserves_of_foreign_exchange_and_gold_2013 text NULL
    ,economy_reserves_of_foreign_exchange_and_gold_reserves_of_foreign_exchange_and_gold_2014 text NULL
    ,economy_reserves_of_foreign_exchange_and_gold_reserves_of_foreign_exchange_and_gold_2020 text NULL
    ,economy_reserves_of_foreign_exchange_and_gold_reserves_of_foreign_exchange_and_gold_31_december_2010 text NULL
    ,economy_reserves_of_foreign_exchange_and_gold_reserves_of_foreign_exchange_and_gold_31_december_2015 text NULL
    ,economy_reserves_of_foreign_exchange_and_gold_reserves_of_foreign_exchange_and_gold_31_december_2016 text NULL
    ,economy_reserves_of_foreign_exchange_and_gold_reserves_of_foreign_exchange_and_gold_31_december_2017 text NULL
    ,economy_taxes_and_other_revenues text NULL
    ,economy_taxes_and_other_revenues_note text NULL
    ,economy_unemployment_rate text NULL
    ,economy_unemployment_rate_note text NULL
    ,economy_unemployment_rate_unemployment_rate_1997 text NULL
    ,economy_unemployment_rate_unemployment_rate_1999 text NULL
    ,economy_unemployment_rate_unemployment_rate_2000 text NULL
    ,economy_unemployment_rate_unemployment_rate_2001 text NULL
    ,economy_unemployment_rate_unemployment_rate_2003 text NULL
    ,economy_unemployment_rate_unemployment_rate_2004 text NULL
    ,economy_unemployment_rate_unemployment_rate_2005 text NULL
    ,economy_unemployment_rate_unemployment_rate_2006 text NULL
    ,economy_unemployment_rate_unemployment_rate_2007 text NULL
    ,economy_unemployment_rate_unemployment_rate_2008 text NULL
    ,economy_unemployment_rate_unemployment_rate_2009 text NULL
    ,economy_unemployment_rate_unemployment_rate_2010 text NULL
    ,economy_unemployment_rate_unemployment_rate_2011 text NULL
    ,economy_unemployment_rate_unemployment_rate_2012 text NULL
    ,economy_unemployment_rate_unemployment_rate_2013 text NULL
    ,economy_unemployment_rate_unemployment_rate_2014 text NULL
    ,economy_unemployment_rate_unemployment_rate_2015 text NULL
    ,economy_unemployment_rate_unemployment_rate_2016 text NULL
    ,economy_unemployment_rate_unemployment_rate_2017 text NULL
    ,economy_unemployment_rate_unemployment_rate_2018 text NULL
    ,economy_unemployment_rate_unemployment_rate_2019 text NULL
    ,economy_unemployment_rate_unemployment_rate_2020 text NULL
    ,energy_crude_oil_exports text NULL
    ,energy_crude_oil_exports_note text NULL
    ,energy_crude_oil_imports text NULL
    ,energy_crude_oil_production text NULL
    ,energy_crude_oil_proved_reserves text NULL
    ,energy_electricity_access_electrification_rural_areas text NULL
    ,energy_electricity_access_electrification_total_population text NULL
    ,energy_electricity_access_electrification_urban_areas text NULL
    ,energy_electricity_consumption text NULL
    ,energy_electricity_exports text NULL
    ,energy_electricity_from_fossil_fuels text NULL
    ,energy_electricity_from_hydroelectric_plants text NULL
    ,energy_electricity_from_nuclear_fuels text NULL
    ,energy_electricity_from_other_renewable_sources text NULL
    ,energy_electricity_imports text NULL
    ,energy_electricity_installed_generating_capacity text NULL
    ,energy_electricity_installed_generating_capacity_note text NULL
    ,energy_electricity_production text NULL
    ,energy_electricity_production_note text NULL
    ,energy_natural_gas_consumption text NULL
    ,energy_natural_gas_consumption_note text NULL
    ,energy_natural_gas_exports text NULL
    ,energy_natural_gas_imports text NULL
    ,energy_natural_gas_imports_note text NULL
    ,energy_natural_gas_production text NULL
    ,energy_natural_gas_production_note text NULL
    ,energy_natural_gas_proved_reserves text NULL
    ,energy_refined_petroleum_products_consumption text NULL
    ,energy_refined_petroleum_products_exports text NULL
    ,energy_refined_petroleum_products_imports text NULL
    ,energy_refined_petroleum_products_production text NULL
    ,environment_air_pollutants_carbon_dioxide_emissions text NULL
    ,environment_air_pollutants_methane_emissions text NULL
    ,environment_air_pollutants_note text NULL
    ,environment_air_pollutants_particulate_matter_emissions text NULL
    ,environment_climate text NULL
    ,environment_climate_note text NULL
    ,environment_environment_current_issues text NULL
    ,environment_environment_current_issues_note text NULL
    ,environment_environment_international_agreements_party_to text NULL
    ,environment_environment_international_agreements_signed_but_not_ratified text NULL
    ,environment_food_insecurity text NULL
    ,environment_food_insecurity_exceptional_shortfall_in_aggregate_food_productionsupplies text NULL
    ,environment_food_insecurity_severe_localized_food_insecurity text NULL
    ,environment_food_insecurity_widespread_lack_of_access text NULL
    ,environment_land_use_agricultural_land text NULL
    ,environment_land_use_agricultural_land_arable_land text NULL
    ,environment_land_use_agricultural_land_permanent_crops text NULL
    ,environment_land_use_agricultural_land_permanent_pasture text NULL
    ,environment_land_use_forest text NULL
    ,environment_land_use_note text NULL
    ,environment_land_use_other text NULL
    ,environment_major_infectious_diseases text NULL
    ,environment_major_infectious_diseases_aerosolized_dust_or_soil_contact_diseases text NULL
    ,environment_major_infectious_diseases_animal_contact_diseases text NULL
    ,environment_major_infectious_diseases_degree_of_risk text NULL
    ,environment_major_infectious_diseases_food_or_waterborne_diseases text NULL
    ,environment_major_infectious_diseases_note text NULL
    ,environment_major_infectious_diseases_respiratory_diseases text NULL
    ,environment_major_infectious_diseases_soil_contact_diseases text NULL
    ,environment_major_infectious_diseases_vectorborne_diseases text NULL
    ,environment_major_infectious_diseases_water_contact_diseases text NULL
    ,environment_revenue_from_coal_coal_revenues text NULL
    ,environment_revenue_from_forest_resources_forest_revenues text NULL
    ,environment_total_renewable_water_resources text NULL
    ,environment_total_renewable_water_resources_note text NULL
    ,environment_total_water_withdrawal_agricultural text NULL
    ,environment_total_water_withdrawal_industrial text NULL
    ,environment_total_water_withdrawal_municipal text NULL
    ,environment_total_water_withdrawal_note text NULL
    ,environment_urbanization_note text NULL
    ,environment_urbanization_rate_of_urbanization text NULL
    ,environment_urbanization_urban_population text NULL
    ,environment_waste_and_recycling_municipal_solid_waste_generated_annually text NULL
    ,environment_waste_and_recycling_municipal_solid_waste_recycled_annually text NULL
    ,environment_waste_and_recycling_note text NULL
    ,environment_waste_and_recycling_percent_of_municipal_solid_waste_recycled text NULL
    ,geography_area_comparative text NULL
    ,geography_area_land text NULL
    ,geography_area_note text NULL
    ,geography_area_total text NULL
    ,geography_area_water text NULL
    ,geography_climate text NULL
    ,geography_climate_note text NULL
    ,geography_coastline text NULL
    ,geography_coastline_note text NULL
    ,geography_elevation_highest_point text NULL
    ,geography_elevation_lowest_point text NULL
    ,geography_elevation_mean_elevation text NULL
    ,geography_elevation_note text NULL
    ,geography_geographic_coordinates text NULL
    ,geography_geography_note text NULL
    ,geography_irrigated_land text NULL
    ,geography_irrigated_land_note text NULL
    ,geography_land_boundaries_border_countries text NULL
    ,geography_land_boundaries_border_sovereign_base_areas text NULL
    ,geography_land_boundaries_french_guiana_total text NULL
    ,geography_land_boundaries_metropolitan_france_total text NULL
    ,geography_land_boundaries_note text NULL
    ,geography_land_boundaries_total text NULL
    ,geography_land_use_agricultural_land text NULL
    ,geography_land_use_agricultural_land_arable_land text NULL
    ,geography_land_use_agricultural_land_permanent_crops text NULL
    ,geography_land_use_agricultural_land_permanent_pasture text NULL
    ,geography_land_use_forest text NULL
    ,geography_land_use_note text NULL
    ,geography_land_use_other text NULL
    ,geography_location text NULL
    ,geography_map_references text NULL
    ,geography_maritime_claims text NULL
    ,geography_maritime_claims_contiguous_zone text NULL
    ,geography_maritime_claims_continental_shelf text NULL
    ,geography_maritime_claims_exclusive_economic_zone text NULL
    ,geography_maritime_claims_exclusive_fishing_zone text NULL
    ,geography_maritime_claims_note text NULL
    ,geography_maritime_claims_territorial_sea text NULL
    ,geography_natural_hazards text NULL
    ,geography_natural_resources text NULL
    ,geography_natural_resources_note text NULL
    ,geography_population_distribution text NULL
    ,geography_population_distribution_note text NULL
    ,geography_terrain text NULL
    ,government_administrative_divisions text NULL
    ,government_administrative_divisions_note text NULL
    ,government_capital_daylight_saving_time text NULL
    ,government_capital_geographic_coordinates text NULL
    ,government_capital_name text NULL
    ,government_capital_note text NULL
    ,government_capital_time_difference text NULL
    ,government_citizenship_citizenship_by_birth text NULL
    ,government_citizenship_citizenship_by_descent_only text NULL
    ,government_citizenship_dual_citizenship_recognized text NULL
    ,government_citizenship_note text NULL
    ,government_citizenship_residency_requirement_for_naturalization text NULL
    ,government_constitution_amendments text NULL
    ,government_constitution_history text NULL
    ,government_constitution_note text NULL
    ,government_country_name_abbreviation text NULL
    ,government_country_name_conventional_long_form text NULL
    ,government_country_name_conventional_short_form text NULL
    ,government_country_name_etymology text NULL
    ,government_country_name_former text NULL
    ,government_country_name_local_long_form text NULL
    ,government_country_name_local_short_form text NULL
    ,government_country_name_note text NULL
    ,government_dependent_areas text NULL
    ,government_dependent_areas_note text NULL
    ,government_diplomatic_representation_from_the_us_branch_offices text NULL
    ,government_diplomatic_representation_from_the_us_chief_of_mission text NULL
    ,government_diplomatic_representation_from_the_us_consulates text NULL
    ,government_diplomatic_representation_from_the_us_consulates_general text NULL
    ,government_diplomatic_representation_from_the_us_email_address_and_website text NULL
    ,government_diplomatic_representation_from_the_us_embassy text NULL
    ,government_diplomatic_representation_from_the_us_fax text NULL
    ,government_diplomatic_representation_from_the_us_mailing_address text NULL
    ,government_diplomatic_representation_from_the_us_note text NULL
    ,government_diplomatic_representation_from_the_us_telephone text NULL
    ,government_diplomatic_representation_in_the_us_chancery text NULL
    ,government_diplomatic_representation_in_the_us_chief_of_mission text NULL
    ,government_diplomatic_representation_in_the_us_consulates text NULL
    ,government_diplomatic_representation_in_the_us_consulates_general text NULL
    ,government_diplomatic_representation_in_the_us_email_address_and_website text NULL
    ,government_diplomatic_representation_in_the_us_fax text NULL
    ,government_diplomatic_representation_in_the_us_honorary_consulates text NULL
    ,government_diplomatic_representation_in_the_us_note text NULL
    ,government_diplomatic_representation_in_the_us_representative_office text NULL
    ,government_diplomatic_representation_in_the_us_telephone text NULL
    ,government_diplomatic_representation_in_the_us_trade_offices text NULL
    ,government_executive_branch_cabinet text NULL
    ,government_executive_branch_chief_of_state text NULL
    ,government_executive_branch_election_results text NULL
    ,government_executive_branch_electionsappointments text NULL
    ,government_executive_branch_head_of_government text NULL
    ,government_executive_branch_head_of_state text NULL
    ,government_executive_branch_note text NULL
    ,government_executive_branch_state_counsellor text NULL
    ,government_flag_description text NULL
    ,government_flag_description_note text NULL
    ,government_government_note text NULL
    ,government_government_type text NULL
    ,government_government_type_note text NULL
    ,government_independence text NULL
    ,government_international_law_organization_participation text NULL
    ,government_international_organization_participation text NULL
    ,government_judicial_branch_highest_courts text NULL
    ,government_judicial_branch_judge_selection_and_term_of_office text NULL
    ,government_judicial_branch_note text NULL
    ,government_judicial_branch_subordinate_courts text NULL
    ,government_legal_system text NULL
    ,government_legislative_branch_description text NULL
    ,government_legislative_branch_election_results text NULL
    ,government_legislative_branch_elections text NULL
    ,government_legislative_branch_note text NULL
    ,government_national_anthem_lyricsmusic text NULL
    ,government_national_anthem_name text NULL
    ,government_national_anthem_note text NULL
    ,government_national_holiday text NULL
    ,government_national_holiday_note text NULL
    ,government_national_symbols text NULL
    ,government_political_parties_and_leaders text NULL
    ,government_political_parties_and_leaders_note text NULL
    ,government_suffrage text NULL
    ,military_and_security_maritime_threats text NULL
    ,military_and_security_military_and_security_forces text NULL
    ,military_and_security_military_and_security_forces_note text NULL
    ,military_and_security_military_and_security_service_personnel_strengths text NULL
    ,military_and_security_military_and_security_service_personnel_strengths_note text NULL
    ,military_and_security_military_deployments text NULL
    ,military_and_security_military_deployments_note text NULL
    ,military_and_security_military_equipment_inventories_and_acquisitions text NULL
    ,military_and_security_military_equipment_inventories_and_acquisitions_note text NULL
    ,military_and_security_military_expenditures text NULL
    ,military_and_security_military_expenditures_military_expenditures_2010 text NULL
    ,military_and_security_military_expenditures_military_expenditures_2011 text NULL
    ,military_and_security_military_expenditures_military_expenditures_2012 text NULL
    ,military_and_security_military_expenditures_military_expenditures_2013 text NULL
    ,military_and_security_military_expenditures_military_expenditures_2014 text NULL
    ,military_and_security_military_expenditures_military_expenditures_2015 text NULL
    ,military_and_security_military_expenditures_military_expenditures_2016 text NULL
    ,military_and_security_military_expenditures_military_expenditures_2017 text NULL
    ,military_and_security_military_expenditures_military_expenditures_2018 text NULL
    ,military_and_security_military_expenditures_military_expenditures_2019 text NULL
    ,military_and_security_military_expenditures_military_expenditures_2020 text NULL
    ,military_and_security_military_expenditures_military_expenditures_2021 text NULL
    ,military_and_security_military_expenditures_note text NULL
    ,military_and_security_military_note text NULL
    ,military_and_security_military_service_age_and_obligation text NULL
    ,military_and_security_military_service_age_and_obligation_note text NULL
    ,people_and_society_age_structure_0_14_years text NULL
    ,people_and_society_age_structure_15_24_years text NULL
    ,people_and_society_age_structure_25_54_years text NULL
    ,people_and_society_age_structure_55_64_years text NULL
    ,people_and_society_age_structure_65_years_and_over text NULL
    ,people_and_society_age_structure_note text NULL
    ,people_and_society_birth_rate text NULL
    ,people_and_society_birth_rate_note text NULL
    ,people_and_society_children_under_the_age_of_5_years_underweight text NULL
    ,people_and_society_children_under_the_age_of_5_years_underweight_note text NULL
    ,people_and_society_contraceptive_prevalence_rate text NULL
    ,people_and_society_contraceptive_prevalence_rate_note text NULL
    ,people_and_society_current_health_expenditure text NULL
    ,people_and_society_current_health_expenditure_note text NULL
    ,people_and_society_death_rate text NULL
    ,people_and_society_death_rate_note text NULL
    ,people_and_society_demographic_profile text NULL
    ,people_and_society_dependency_ratios_elderly_dependency_ratio text NULL
    ,people_and_society_dependency_ratios_note text NULL
    ,people_and_society_dependency_ratios_potential_support_ratio text NULL
    ,people_and_society_dependency_ratios_total_dependency_ratio text NULL
    ,people_and_society_dependency_ratios_youth_dependency_ratio text NULL
    ,people_and_society_drinking_water_source_improved_rural text NULL
    ,people_and_society_drinking_water_source_improved_total text NULL
    ,people_and_society_drinking_water_source_improved_urban text NULL
    ,people_and_society_drinking_water_source_note text NULL
    ,people_and_society_drinking_water_source_unimproved_rural text NULL
    ,people_and_society_drinking_water_source_unimproved_total text NULL
    ,people_and_society_drinking_water_source_unimproved_urban text NULL
    ,people_and_society_education_expenditures text NULL
    ,people_and_society_education_expenditures_note text NULL
    ,people_and_society_ethnic_groups text NULL
    ,people_and_society_ethnic_groups_note text NULL
    ,people_and_society_hivaids_adult_prevalence_rate text NULL
    ,people_and_society_hivaids_adult_prevalence_rate_note text NULL
    ,people_and_society_hivaids_deaths text NULL
    ,people_and_society_hivaids_deaths_note text NULL
    ,people_and_society_hivaids_people_living_with_hivaids text NULL
    ,people_and_society_hivaids_people_living_with_hivaids_note text NULL
    ,people_and_society_hospital_bed_density text NULL
    ,people_and_society_hospital_bed_density_note text NULL
    ,people_and_society_infant_mortality_rate_female text NULL
    ,people_and_society_infant_mortality_rate_male text NULL
    ,people_and_society_infant_mortality_rate_note text NULL
    ,people_and_society_infant_mortality_rate_total text NULL
    ,people_and_society_languages text NULL
    ,people_and_society_languages_languages text NULL
    ,people_and_society_languages_major_language_samples text NULL
    ,people_and_society_languages_note text NULL
    ,people_and_society_life_expectancy_at_birth_female text NULL
    ,people_and_society_life_expectancy_at_birth_male text NULL
    ,people_and_society_life_expectancy_at_birth_note text NULL
    ,people_and_society_life_expectancy_at_birth_total_population text NULL
    ,people_and_society_literacy_definition text NULL
    ,people_and_society_literacy_female text NULL
    ,people_and_society_literacy_male text NULL
    ,people_and_society_literacy_note text NULL
    ,people_and_society_literacy_total_population text NULL
    ,people_and_society_major_infectious_diseases text NULL
    ,people_and_society_major_infectious_diseases_aerosolized_dust_or_soil_contact_diseases text NULL
    ,people_and_society_major_infectious_diseases_animal_contact_diseases text NULL
    ,people_and_society_major_infectious_diseases_degree_of_risk text NULL
    ,people_and_society_major_infectious_diseases_food_or_waterborne_diseases text NULL
    ,people_and_society_major_infectious_diseases_note text NULL
    ,people_and_society_major_infectious_diseases_respiratory_diseases text NULL
    ,people_and_society_major_infectious_diseases_soil_contact_diseases text NULL
    ,people_and_society_major_infectious_diseases_vectorborne_diseases text NULL
    ,people_and_society_major_infectious_diseases_water_contact_diseases text NULL
    ,people_and_society_major_urban_areas_population text NULL
    ,people_and_society_major_urban_areas_population_note text NULL
    ,people_and_society_maternal_mortality_ratio text NULL
    ,people_and_society_maternal_mortality_ratio_note text NULL
    ,people_and_society_median_age_female text NULL
    ,people_and_society_median_age_male text NULL
    ,people_and_society_median_age_note text NULL
    ,people_and_society_median_age_total text NULL
    ,people_and_society_mothers_mean_age_at_first_birth text NULL
    ,people_and_society_mothers_mean_age_at_first_birth_note text NULL
    ,people_and_society_nationality_adjective text NULL
    ,people_and_society_nationality_note text NULL
    ,people_and_society_nationality_noun text NULL
    ,people_and_society_net_migration_rate text NULL
    ,people_and_society_net_migration_rate_note text NULL
    ,people_and_society_obesity_adult_prevalence_rate text NULL
    ,people_and_society_obesity_adult_prevalence_rate_note text NULL
    ,people_and_society_people_note text NULL
    ,people_and_society_physicians_density text NULL
    ,people_and_society_physicians_density_note text NULL
    ,people_and_society_population text NULL
    ,people_and_society_population_distribution text NULL
    ,people_and_society_population_distribution_note text NULL
    ,people_and_society_population_growth_rate text NULL
    ,people_and_society_population_growth_rate_note text NULL
    ,people_and_society_population_note text NULL
    ,people_and_society_religions text NULL
    ,people_and_society_religions_note text NULL
    ,people_and_society_sanitation_facility_access_improved_rural text NULL
    ,people_and_society_sanitation_facility_access_improved_total text NULL
    ,people_and_society_sanitation_facility_access_improved_urban text NULL
    ,people_and_society_sanitation_facility_access_note text NULL
    ,people_and_society_sanitation_facility_access_unimproved_rural text NULL
    ,people_and_society_sanitation_facility_access_unimproved_total text NULL
    ,people_and_society_sanitation_facility_access_unimproved_urban text NULL
    ,people_and_society_school_life_expectancy_primary_to_tertiary_education_female text NULL
    ,people_and_society_school_life_expectancy_primary_to_tertiary_education_male text NULL
    ,people_and_society_school_life_expectancy_primary_to_tertiary_education_note text NULL
    ,people_and_society_school_life_expectancy_primary_to_tertiary_education_total text NULL
    ,people_and_society_sex_ratio_0_14_years text NULL
    ,people_and_society_sex_ratio_15_24_years text NULL
    ,people_and_society_sex_ratio_25_54_years text NULL
    ,people_and_society_sex_ratio_55_64_years text NULL
    ,people_and_society_sex_ratio_65_years_and_over text NULL
    ,people_and_society_sex_ratio_at_birth text NULL
    ,people_and_society_sex_ratio_note text NULL
    ,people_and_society_sex_ratio_total_population text NULL
    ,people_and_society_total_fertility_rate text NULL
    ,people_and_society_total_fertility_rate_note text NULL
    ,people_and_society_unemployment_youth_ages_15_24_female text NULL
    ,people_and_society_unemployment_youth_ages_15_24_male text NULL
    ,people_and_society_unemployment_youth_ages_15_24_note text NULL
    ,people_and_society_unemployment_youth_ages_15_24_total text NULL
    ,people_and_society_urbanization_note text NULL
    ,people_and_society_urbanization_rate_of_urbanization text NULL
    ,people_and_society_urbanization_urban_population text NULL
    ,terrorism_terrorist_groups text NULL
    ,terrorism_terrorist_groups_note text NULL
    ,transnational_issues_disputes_international text NULL
    ,transnational_issues_illicit_drugs text NULL
    ,transnational_issues_refugees_and_internally_displaced_persons_idps text NULL
    ,transnational_issues_refugees_and_internally_displaced_persons_note text NULL
    ,transnational_issues_refugees_and_internally_displaced_persons_refugees_country_of_origin text NULL
    ,transnational_issues_refugees_and_internally_displaced_persons_stateless_persons text NULL
    ,transnational_issues_trafficking_in_persons_current_situation text NULL
    ,transnational_issues_trafficking_in_persons_tier_rating text NULL
    ,transportation_airports_total text NULL
    ,transportation_airports_with_paved_runways_1524_to_2437_m text NULL
    ,transportation_airports_with_paved_runways_2438_to_3047_m text NULL
    ,transportation_airports_with_paved_runways_914_to_1523_m text NULL
    ,transportation_airports_with_paved_runways_over_3047_m text NULL
    ,transportation_airports_with_paved_runways_total text NULL
    ,transportation_airports_with_paved_runways_under_914_m text NULL
    ,transportation_airports_with_unpaved_runways_1524_to_2437_m text NULL
    ,transportation_airports_with_unpaved_runways_2438_to_3047_m text NULL
    ,transportation_airports_with_unpaved_runways_914_to_1523_m text NULL
    ,transportation_airports_with_unpaved_runways_over_3047_m text NULL
    ,transportation_airports_with_unpaved_runways_total text NULL
    ,transportation_airports_with_unpaved_runways_under_914_m text NULL
    ,transportation_civil_aircraft_registration_country_code_prefix text NULL
    ,transportation_heliports text NULL
    ,transportation_merchant_marine_by_type text NULL
    ,transportation_merchant_marine_note text NULL
    ,transportation_merchant_marine_total text NULL
    ,transportation_national_air_transport_system_annual_freight_traffic_on_registered_air_carriers text NULL
    ,transportation_national_air_transport_system_annual_passenger_traffic_on_registered_air_carriers text NULL
    ,transportation_national_air_transport_system_inventory_of_registered_aircraft_operated_by_air_carriers text NULL
    ,transportation_national_air_transport_system_number_of_registered_air_carriers text NULL
    ,transportation_pipelines text NULL
    ,transportation_ports_and_terminals text NULL
    ,transportation_ports_and_terminals_cargo_ports text NULL
    ,transportation_ports_and_terminals_container_ports_teus text NULL
    ,transportation_ports_and_terminals_cruise_departure_ports_passengers text NULL
    ,transportation_ports_and_terminals_cruise_ports text NULL
    ,transportation_ports_and_terminals_cruiseferry_ports text NULL
    ,transportation_ports_and_terminals_dry_bulk_cargo_ports text NULL
    ,transportation_ports_and_terminals_lake_ports text NULL
    ,transportation_ports_and_terminals_lng_terminals_export text NULL
    ,transportation_ports_and_terminals_lng_terminals_import text NULL
    ,transportation_ports_and_terminals_major_seaports text NULL
    ,transportation_ports_and_terminals_note text NULL
    ,transportation_ports_and_terminals_oil_terminals text NULL
    ,transportation_ports_and_terminals_river_and_lake_ports text NULL
    ,transportation_ports_and_terminals_river_or_lake_ports text NULL
    ,transportation_ports_and_terminals_river_ports text NULL
    ,transportation_railways text NULL
    ,transportation_railways_broad_gauge text NULL
    ,transportation_railways_dual_gauge text NULL
    ,transportation_railways_narrow_gauge text NULL
    ,transportation_railways_note text NULL
    ,transportation_railways_other text NULL
    ,transportation_railways_standard_gauge text NULL
    ,transportation_railways_total text NULL
    ,transportation_roadways text NULL
    ,transportation_roadways_government_control text NULL
    ,transportation_roadways_highways text NULL
    ,transportation_roadways_non_urban text NULL
    ,transportation_roadways_note text NULL
    ,transportation_roadways_paved text NULL
    ,transportation_roadways_pavedoiled_gravel text NULL
    ,transportation_roadways_private_and_forest_roads text NULL
    ,transportation_roadways_total text NULL
    ,transportation_roadways_turkish_cypriot_control text NULL
    ,transportation_roadways_unpaved text NULL
    ,transportation_roadways_urban text NULL
    ,transportation_transportation_note text NULL
    ,transportation_waterways    text NULL
)
